### ISSUE TITLE
Keywords and refresh

### ISSUE THREAD

**Issue by jacobcarey** [klovell96/own_bot#18]
Hey, 

I am enjoying your script and hoping to use it myself. Just to note, both "registration" and "postcode" are on the waiting holding page this year, and therefore the script will immediately exit. 

I also moved the refresh and sleep to the else statement, if you magically get through on the first request, you would be refreshing it, and potentially throwing yourself. Refreshing after the check should help with this. 

        else:
            print("Not found, refreshing.")
            driver.refresh()
            time.sleep(1.25)

**Comment by kitkat-96** [comment]
How do you know about the registration and postcode on the queue page?

**Comment by jacobcarey** [comment]
It was live before:On 16 Nov 2023, at 16:52, klovell96 ***@***.***> wrote:﻿
How do you know about the registration and postcode on the queue page?

**Comment by jacobcarey** [comment]
It was live for a bit before: 

![IMG_3013](https://github.com/klovell96/own_bot/assets/11725664/9f166862-94ec-4143-be49-a24826973dff)

**Comment by kitkat-96** [comment]
Thank you! I've updated it to read deposit instead. Hope this works.

**Comment by jacobcarey** [comment]
Did you have any success?

**Comment by kitkat-96** [comment]
No, you?

**Comment by jacobcarey** [comment]
A friend got me a ticket, but no luck with the script unfortunately. Stuck on the waiting page.
